log:
  image: wise2c/harbor-log
  container_name: wise2c-reg-log
  volumes:
    - ${LOGDIR}:/var/log/docker/
  ports:
    - 1514:514
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"
registry:
  image: library/registry:2.4.0
  container_name: wise2c-reg-registry
  volumes:
    - ${REGIMGDIR}:/storage
    - ${REGCFGDIR}:/etc/registry/
  environment:
    - GODEBUG=netdns=cgo
  ports:
    - 5001:5001
  command:
    ["serve", "/etc/registry/config.yml"]
  #depends_on:
  #  - log
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "registry"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1
mysql:
  image: wise2c/harbor-mysql
  container_name: wise2c-reg-mysql
  volumes:
    - ${DBDIR}:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${DBPASSWD}
  #depends_on:
  #  - log
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "mysql"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1
ui:
  image: wise2c/harbor-ui
  container_name: wise2c-reg-ui
  environment:
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_USR=root
    - MYSQL_PWD=root123
    - REGISTRY_URL=http://registry:5000
    - UI_URL=http://ui
    - CONFIG_PATH=/etc/ui/app.conf
    - HARBOR_REG_URL=${UIREGURL}
    - HARBOR_ADMIN_PASSWORD=${UIRADMINURL}
    - HARBOR_URL=${UIURL}
    - AUTH_MODE=db_auth
    - LDAP_URL=ldaps://ldap.mydomain.com
    - LDAP_BASE_DN=uid=%s,ou=people,dc=mydomain,dc=com
    - UI_SECRET=Nwzq1exKgmgzPviU
    - SELF_REGISTRATION=on
    - LOG_LEVEL=debug
    - GODEBUG=netdns=cgo
    - EXT_ENDPOINT=${UIURL}
    - TOKEN_URL=http://ui
    - VERIFY_REMOTE_CERT=on
  volumes:
    - ${UICFGDIR}:/etc/ui
  #depends_on:
  #  - log
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "ui"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1
jobservice:
  image: wise2c/harbor-jobservice
  container_name: wise2c-reg-jobservice
  environment:
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_USR=root
    - MYSQL_PWD=root123
    - UI_SECRET=Nwzq1exKgmgzPviU
    - CONFIG_PATH=/etc/jobservice/app.conf
    - REGISTRY_URL=http://registry:5000
    - VERIFY_REMOTE_CERT=on
    - MAX_JOB_WORKERS=3
    - LOG_LEVEL=debug
    - LOG_DIR=/var/log/jobs
    - GODEBUG=netdns=cgo
    - EXT_ENDPOINT=${UIURL}
    - TOKEN_URL=http://ui
  volumes:
    - ${JOBSRVSLOGDIR}:/var/log/jobs
    - ${JOBSRVSCFGDIR}/app.conf:/etc/jobservice/app.conf
  #depends_on:
  #  - ui
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "jobservice"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1
proxy:
  image: library/nginx:1.9
  volumes:
    - ${PROXYCFGDIR}:/etc/nginx
  ports:
    - 80:80
    - 443:443
  #depends_on:
  #  - mysql
  #  - registry
  #  - ui
  #  - log
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "proxy"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1