registry-datavolume:
  image: busybox
  volumes: 
    - ${STORAGEDIR}:/storage
    - ${MYSQLDIR}:/var/lib/mysql
    - ${LOGDIR}:/var/log
    - ${CFGDIR}:/etc
  net: none
  command: /bin/true
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"
    io.rancher.container.start_once: true

log:
  image: wise2c/harbor-log
  container_name: wise2c-reg-log
  #volumes_from:
  #  - registry-datavolume
  ports:
    - 1514:514
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"