prepare:
  image: wise2c/harbor-prepare
  container_name: wise2c-reg-prepare
  volumes:
    - ${EXTERNAL_DIR}:/harbor
    - ${OFFICIAL_CRT_DIR}:/cert
  net: none
  command: /usr/local/bin/python /root/prepare.py
  environment:
    - HOSTNAME=${HOSTNAME}
    - UI_URL_PROTOCOL=${UI_URL_PROTOCOL}
    - EMAIL_SERVER=${EMAIL_SERVER}
    - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
    - EMAIL_USERNAME=${EMAIL_USERNAME}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    - EMAIL_FROM=${EMAIL_FROM}
    - EMAIL_SSL=${EMAIL_SSL}
    - HARBOR_ADMIN_PASSWORD=${HARBOR_ADMIN_PASSWORD}
    - AUTH_MODE=${AUTH_MODE}
    - LDAP_URL=${LDAP_URL}
    - LDAP_BASEDN=${LDAP_BASEDN}
    - DB_PASSWORD=${DB_PASSWORD}
    - SELF_REGISTRATION=${SELF_REGISTRATION}
  labels:
    io.rancher.container.start_once: 'true'

