registry-data-volume:
  image: busybox:latest
  volumes: 
  - ${STORAGEDIR}:/storage
  - ${MYSQLDIR}:/var/lib/mysql
  - ${LOGDIR}:/var/log
  - ${CFGDIR}:/etc
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"
    io.rancher.container.start_once: true

