log:
  image: wise2c/harbor-log
  container_name: wise2c-reg-log
  ports:
    - 1514:514
  volumes:
    - ${LOGDIR}/harbor:/var/log/docker/
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"
proxy:
  image: library/nginx:1.9
  container_name: wise2c-reg-proxy
  ports:
    - 80:80
    - 443:443
  #links:
  #  - registry
  #  - ui
  #  - jobservice
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://log:514"
      syslog-tag: "proxy"
  volumes:
    - ${CFGDIR}/nginx:/etc/nginx
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1