registry-datavolume:
  image: busybox
  volumes:
    - ${LOGDIR}/harbor:/var/log/docker/
    - ${DATADIR}/job_logs:/var/log/jobs
    - ${DATADIR}/database:/var/lib/mysql
    - ${DATADIR}/registry:/storage
    - ${CFGDIR}/ui:/etc/ui
    - ${CFGDIR}/nginx:/etc/nginx
    - ${CFGDIR}/registry:/etc/registry/
  net: none
  command: /bin/true
  labels:
    io.rancher.container.start_once: true
    io.rancher.sidekicks: log,mysql

log:
  image: wise2c/harbor-log
  volumes_from:
    - registry-datavolume
  ports:
    - 1514:514
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"

mysql:
  image: wise2c/harbor-mysql
  container_name: wise2c-reg-mysql
  volumes_from:
    - registry-datavolume
  environment:
    - MYSQL_ROOT_PASSWORD=${DBPASSWD}
  #log_driver: "syslog"
  #log_opt:
  #    syslog-address: "tcp://log:514"
  #    syslog-tag: "mysql"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1
