log:
  image: wise2c/harbor-log
  ports:
    - 1514:514
  volumes:
    - ${LOGDIR}/harbor:/var/log/docker/
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"

mysql:
  image: wise2c/harbor-mysql
  container_name: wise2c-reg-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${DBPASSWD}
  #log_driver: "syslog"
  #log_opt:
  #    syslog-address: "tcp://log:1514"
  #    syslog-tag: "mysql"
  ports:
    - 3306:3306
  volumes:
    - ${DATADIR}/database:/var/lib/mysql
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1

registry:
  image: library/registry:2.4.0
  container_name: wise2c-reg-registry
  environment:
    - GODEBUG=netdns=cgo
  ports:
    - 5001:5001
  command:
    ["serve", "/etc/registry/config.yml"]
  #log_driver: "syslog"
  #log_opt:
  #    syslog-address: "tcp://log:1514"
  #    syslog-tag: "registry"
  volumes:
    - ${DATADIR}/registry:/storage
    - ${CFGDIR}/registry:/etc/registry/
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1
ui:
  image: wise2c/harbor-ui
  container_name: wise2c-reg-ui
  environment:
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_USR=root
    - MYSQL_PWD=root123
    - REGISTRY_URL=http://registry:5000
    - UI_URL=http://ui
    - CONFIG_PATH=/etc/ui/app.conf
    - HARBOR_REG_URL=http://${URL}
    - HARBOR_ADMIN_PASSWORD=${UIRADMINPWD}
    - HARBOR_URL=https://${URL}
    - AUTH_MODE=db_auth
    - LDAP_URL=ldaps://ldap.mydomain.com
    - LDAP_BASE_DN=uid=%s,ou=people,dc=mydomain,dc=com
    - UI_SECRET=Nwzq1exKgmgzPviU
    - SELF_REGISTRATION=on
    - LOG_LEVEL=debug
    - GODEBUG=netdns=cgo
    - EXT_ENDPOINT=https://${URL}
    - TOKEN_URL=http://ui
    - VERIFY_REMOTE_CERT=on
  links:
    - mysql
  ports:
    - 8010:80
    - 8443:443
  volumes:
    - ${CFGDIR}/ui:/etc/ui
  #log_driver: "syslog"
  #log_opt:
  #    syslog-address: "tcp://log:1514"
  #    syslog-tag: "ui"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1
jobservice:
  image: wise2c/harbor-jobservice
  container_name: wise2c-reg-jobservice
  environment:
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_USR=root
    - MYSQL_PWD=root123
    - UI_SECRET=Nwzq1exKgmgzPviU
    - CONFIG_PATH=/etc/jobservice/app.conf
    - REGISTRY_URL=http://registry:5000
    - VERIFY_REMOTE_CERT=on
    - MAX_JOB_WORKERS=3
    - LOG_LEVEL=debug
    - LOG_DIR=/var/log/jobs
    - GODEBUG=netdns=cgo
    - EXT_ENDPOINT=${UIURL}
    - TOKEN_URL=http://ui
  links:
    - mysql
  #log_driver: "syslog"
  #log_opt:
  #    syslog-address: "tcp://log:1514"
  #    syslog-tag: "jobservice"
  volumes:
    - ${DATADIR}/job_logs:/var/log/jobs
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1
proxy:
  image: library/nginx:1.9
  ports:
    - 80:80
    - 443:443
  links:
    - registry
    - ui
  #log_driver: "syslog"
  #log_opt:
  #    syslog-address: "tcp://log:1514"
  #    syslog-tag: "proxy"
  volumes:
    - ${CFGDIR}/nginx:/etc/nginx
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1