registry-datavolume:
  image: busybox
  volumes: 
    - ${LOGDIR}/harbor:/var/log/docker/
    - ${DATADIR}/job_logs:/var/log/jobs
    - ${DATADIR}/database:/var/lib/mysql
    - ${DATADIR}/registry:/storage
    - ${CFGDIR}/ui:/etc/ui
    - ${CFGDIR}/nginx:/etc/nginx
    - ${CFGDIR}/registry:/etc/registry/
  net: none
  command: /bin/true
  labels:
    io.rancher.container.start_once: true
    io.rancher.sidekicks: log

log:
  image: wise2c/harbor-log
  volumes_from:
    - registry-datavolume
  ports:
    - 1514:514
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"