prepare:
  image: registry.aliyuncs.com/ljchen/harbor-prepare
  container_name: wise2c-reg-prepare
  volume_driver: ${VOLUME_DRIVER}
  volumes:
    - ${EXTERNAL_DIR}:/harbor
    - ${EXTERNAL_DIR}-log:/var/log/docker/
    - ${EXTERNAL_DIR}-storage:/storage
    - ${EXTERNAL_DIR}-config-registry:/etc/registry/
    - ${EXTERNAL_DIR}-database:/var/lib/mysql
    - ${EXTERNAL_DIR}-config-ui:/etc/ui
    - ${EXTERNAL_DIR}-log-job_logs:/var/log/jobs
    - ${EXTERNAL_DIR}-config-jobservice:/etc/jobservice
    - ${EXTERNAL_DIR}-config-nginx:/etc/nginx
  net: none
  command: /usr/local/bin/python /root/prepare.py
  environment:
    - HOSTNAME=${HOSTNAME}
    - UI_URL_PROTOCOL=${UI_URL_PROTOCOL}
    - EMAIL_SERVER=${EMAIL_SERVER}
    - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
    - EMAIL_USERNAME=${EMAIL_USERNAME}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    - EMAIL_FROM=${EMAIL_FROM}
    - EMAIL_SSL=${EMAIL_SSL}
    - HARBOR_ADMIN_PASSWORD=${HARBOR_ADMIN_PASSWORD}
    - AUTH_MODE=${AUTH_MODE}
    - LDAP_URL=${LDAP_URL}
    - LDAP_BASEDN=${LDAP_BASEDN}
    - DB_PASSWORD=${DB_PASSWORD}
    - SELF_REGISTRATION=${SELF_REGISTRATION}
    - CUSTOMIZE_CRT=${CUSTOMIZE_CRT}
    - CRT_COUNTRY=${CRT_COUNTRY}
    - CRT_STATE=${CRT_STATE}
    - CRT_LOCATION=${CRT_LOCATION}
    - CRT_ORGANIZATION=${CRT_ORGANIZATION}
    - CRT_ORGANIZATIONALUNIT=${CRT_ORGANIZATIONALUNIT}
    - CRT_COMMONNAME=${CRT_COMMONNAME}
    - CRT_EMAIL=${CRT_EMAIL}
    - MAX_JOB_WORKERS=${MAX_JOB_WORKERS}
    - VERIFY_REMOTE_CERT=${VERIFY_REMOTE_CERT}
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.sidekicks: log, registry, mysql, ui, jobservice, proxy

log:
  image: registry.aliyuncs.com/ljchen/harbor-log
  container_name: wise2c-reg-log
  ports:
    - 1514:514
  links:
    - prepare
  volume_driver: ${VOLUME_DRIVER}
  volumes:
    - ${EXTERNAL_DIR}/log:/var/log/docker/
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"

registry:
  image: library/registry:2.4.0
  container_name: wise2c-reg-registry
  environment:
    - GODEBUG=netdns=cgo
  ports:
    - 5001:5001
  links:
    - prepare
  command:
    ["serve", "/etc/registry/config.yml"]
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "registry"
  #volume_driver: ${VOLUME_DRIVER}
  #volumes:
  #  - ${EXTERNAL_DIR}/storage:/storage
  #  - ${EXTERNAL_DIR}/config/registry:/etc/registry/
  volumes_from: prepare

    
mysql:
  image: registry.aliyuncs.com/ljchen/harbor-mysql
  container_name: wise2c-reg-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "mysql"
  ports:
    - 3306:3306
  links:
    - prepare
  #volume_driver: ${VOLUME_DRIVER}
  #volumes:
  #  - ${EXTERNAL_DIR}/database:/var/lib/mysql
  volumes_from: prepare

ui:
  image: registry.aliyuncs.com/ljchen/harbor-ui
  container_name: wise2c-reg-ui
  links:
    - mysql
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "ui"
  #volume_driver: ${VOLUME_DRIVER}
  #volumes:
  #  - ${EXTERNAL_DIR}/config/ui:/etc/ui
  volumes_from: prepare

jobservice:
  image: registry.aliyuncs.com/ljchen/harbor-jobservice
  container_name: wise2c-reg-jobservice
  links:
    - mysql
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "jobservice"
  #volume_driver: ${VOLUME_DRIVER}
  #volumes:
  #  - ${EXTERNAL_DIR}/log/job_logs:/var/log/jobs
  #  - ${EXTERNAL_DIR}/config/jobservice:/etc/jobservice
  volumes_from: prepare

proxy:
  image: library/nginx:1.9
  container_name: wise2c-reg-mysql
  ports:
    - 80:80
    - 443:443
  links:
    - registry
    - ui
    - jobservice
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "proxy"
  #volume_driver: ${VOLUME_DRIVER}
  #volumes:
  #  - ${EXTERNAL_DIR}/config/nginx:/etc/nginx
  volumes_from: prepare
