prepare:
  image: wise2c/harbor-prepare
  container_name: wise2c-reg-prepare
  volumes:
    - ${EXTERNAL_DIR}:/harbor
    - ${OFFICIAL_CRT_DIR}:/cert
  net: none
  command: /usr/local/bin/python /root/prepare.py
  environment:
    - HOSTNAME=${HOSTNAME}
    - UI_URL_PROTOCOL=${UI_URL_PROTOCOL}
    - EMAIL_SERVER=${EMAIL_SERVER}
    - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
    - EMAIL_USERNAME=${EMAIL_USERNAME}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    - EMAIL_FROM=${EMAIL_FROM}
    - EMAIL_SSL=${EMAIL_SSL}
    - HARBOR_ADMIN_PASSWORD=${HARBOR_ADMIN_PASSWORD}
    - AUTH_MODE=${AUTH_MODE}
    - LDAP_URL=${LDAP_URL}
    - LDAP_BASEDN=${LDAP_BASEDN}
    - DB_PASSWORD=${DB_PASSWORD}
    - SELF_REGISTRATION=${SELF_REGISTRATION}
    - CUSTOMIZE_CRT=${CUSTOMIZE_CRT}
    - CRT_COUNTRY=${CRT_COUNTRY}
    - CRT_STATE=${CRT_STATE}
    - CRT_LOCATION=${CRT_LOCATION}
    - CRT_ORGANIZATION=${CRT_ORGANIZATION}
    - CRT_ORGANIZATIONALUNIT=${CRT_ORGANIZATIONALUNIT}
    - CRT_COMMONNAME=${CRT_COMMONNAME}
    - CRT_EMAIL=${CRT_EMAIL}
    - MAX_JOB_WORKERS=${MAX_JOB_WORKERS}
    - VERIFY_REMOTE_CERT=${VERIFY_REMOTE_CERT}
  labels:
    io.rancher.container.start_once: 'true'

log:
  image: wise2c/harbor-log
  container_name: wise2c-reg-log
  ports:
    - 1514:514
  links:
    - prepare
  volumes:
    - ${EXTERNAL_DIR}/log:/var/log/docker/
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"

registry:
  image: library/registry:2.4.0
  container_name: wise2c-reg-registry
  environment:
    - GODEBUG=netdns=cgo
  ports:
    - 5001:5001
  links:
    - prepare
  command:
    ["serve", "/etc/registry/config.yml"]
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "registry"
  volumes:
    - ${EXTERNAL_DIR}/storage:/storage
    - ${EXTERNAL_DIR}/config/registry:/etc/registry/
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1
    
mysql:
  image: wise2c/harbor-mysql
  container_name: wise2c-reg-mysql
  env_file:
    - ${EXTERNAL_DIR}/config/db/env
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "mysql"
  ports:
    - 3306:3306
  links:
    - prepare
  volumes:
    - ${EXTERNAL_DIR}/database:/var/lib/mysql
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1

ui:
  image: wise2c/harbor-ui
  container_name: wise2c-reg-ui
  env_file:
    - ${EXTERNAL_DIR}/config/ui/env
  links:
    - mysql
  volumes:
    - ${EXTERNAL_DIR}/config/ui:/etc/ui
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "ui"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1

jobservice:
  image: wise2c/harbor-jobservice
  container_name: wise2c-reg-jobservice
  env_file:
    - ${EXTERNAL_DIR}/config/jobservice/env
  links:
    - mysql
  volumes:
    - ${EXTERNAL_DIR}/log/job_logs:/var/log/jobs
    - ${EXTERNAL_DIR}/config/jobservice/app.conf:/etc/jobservice/app.conf
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "jobservice"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1

proxy:
  image: library/nginx:1.9
  container_name: wise2c-reg-mysql
  ports:
    - 80:80
    - 443:443
  links:
    - registry
    - ui
    - jobservice
  volumes:
    - ${EXTERNAL_DIR}/config/nginx:/etc/nginx
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://127.0.0.1:1514"
      syslog-tag: "proxy"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1