registry-datavolume:
  image: busybox
  volumes: 
    - /storage
    - /var/lib/mysql
    - /var/log/docker
    - /etc/cfg
  net: none
  command: /bin/true
  labels:
    io.rancher.container.start_once: true

log:
  image: wise2c/harbor-log
  container_name: wise2c-reg-log
  volumes_from:
    - registry-datavolume
  ports:
    - 1514:514
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"