registry-datavolume:
  image: busybox
  volumes:
    - ${LOGDIR}/harbor:/var/log/docker/
    - ${DATADIR}/job_logs:/var/log/jobs
    - ${DATADIR}/database:/var/lib/mysql
    - ${DATADIR}/registry:/storage
    - ${CFGDIR}/ui:/etc/ui
    - ${CFGDIR}/nginx:/etc/nginx
    - ${CFGDIR}/registry:/etc/registry/
  net: none
  command: /bin/true
  labels:
    io.rancher.container.start_once: true
    io.rancher.sidekicks: log,registry

log:
  image: wise2c/harbor-log
  volumes_from:
    - registry-datavolume
  ports:
    - 1514:514
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"

registry:
  image: library/registry:2.4.0
  container_name: wise2c-reg-registry
  volumes_from:
    - registry-datavolume
  environment:
    - GODEBUG=netdns=cgo
  ports:
    - 5001:5001
  command:
    ["serve", "/etc/registry/config.yml"]
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://log:1514"
      syslog-tag: "registry"
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1


