registry-datavolume:
  image: busybox
  volumes: 
    - ${STORAGEDIR}:/storage
    - ${MYSQLDIR}:/var/lib/mysql
    - ${LOGDIR}:/var/log
  net: none
  command: /bin/true
  labels:
    io.rancher.container.start_once: true

log:
  image: wise2c/harbor-log
  volumes_from:
    - registry-datavolume
  ports:
    - 1514:514