registry-datavolume:
  image: busybox:latest
  volumes: 
  - /storage
  - /var/lib/mysql
  - /var/log
  - /etc
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"
    io.rancher.container.start_once: true

