log:
  image: wise2c/harbor-log
  container_name: wise2c-reg-log
  ports:
    - 1514:514
  volumes:
    - ${LOGDIR}/harbor:/var/log/docker/
  labels:
    io.rancher.scheduler.affinity: "hostname=agent-1"

registry:
  image: library/registry:2.4.0
  container_name: wise2c-reg-registry
  environment:
    - GODEBUG=netdns=cgo
  ports:
    - 5001:5001
  command:
    ["serve", "/etc/registry/config.yml"]
  log_driver: "syslog"
  log_opt:
      syslog-address: "tcp://log:514"
      syslog-tag: "registry"
  links:
    - log
  volumes:
    - ${DATADIR}/registry:/storage
    - ${CFGDIR}/registry:/etc/registry/
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=agent-1