.catalog:
  name: Wise2C-Registry
  version: v0.1
  description: |
    Wise2c Docker Registry
  maintainer: "Chen Leji <chenleji@wise2c.com>"
  questions:

    - variable: "OFFICIAL_CRT_DIR"
      label: "Official CRT Forlder"
      description: "Wise2C Registry Official CRT Forlder"
      default: "/"
      type: string

    - variable: "EXTERNAL_DIR"
      label: "External Shared Storage Forlder"
      description: "External shared storage forlder, which is used to store the config/data/log info."
      required: true
      default: "/data"
      type: string

    - variable: "HOSTNAME"
      label: "Hostname"
      description: "The target host's hostname, which is used to access the UI and the registry service."
      required: true
      default: "reg.wise2c.com"
      type: string

    - variable: "UI_URL_PROTOCOL"
      label: "URL Protocol"
      description: "The protocol used to access the UI and the token/notification service. By default, this is http. "
      required: true
      default: "https"
      type: enum
      options:
        - https
        - http

    - variable: "EMAIL_SERVER"
      label: "Email Server"
      description: "These parameters are needed for Harbor to be able to send a user a 'password reset' email."
      required: true
      default: "smtp.mydomain.com"
      type: string
