.catalog:
  name: "Wise2C-Registry"
  version: "v0.1"
  description: "Wise2c Docker Registry"
  uuid: registry-1
  questions: 
    - variable: "EXTERNAL_DIR"
      label: "Wise2C Registry External Shared Storage Forlder"
      description: "External shared storage forlder, which is used to store the config/data/log info."
      required: true
      default: "/data"
      type: "string"

    - variable: "HOSTNAME"
      label: "Wise2C Registry Hostname"
      description: "The target host's hostname, which is used to access the UI and the registry service. It should be the IP address or the fully qualified domain name (FQDN) of your target machine, e.g., 192.168.1.10 or reg.yourdomain.com. Do NOT use localhost or 127.0.0.1 for the hostname - the registry service needs to be accessible by external clients!"
      required: true
      default: "reg.wise2c.com"
      type: "string"

    - variable: "UI_URL_PROTOCOL"
      label: "Wise2C Registry URL Protocol"
      description: "The protocol used to access the UI and the token/notification service. By default, this is http. "
      required: true
      type: "enum"
      options:
        - https
        - http

    - variable: "EMAIL_SERVER"
      label: "Wise2C Registry Email Server"
      description: "These parameters are needed for Harbor to be able to send a user a "password reset" email, and are only necessary if that functionality is needed. Also, do note that by default SSL connectivity is not enabled - if your SMTP server requires SSL, but does not support STARTTLS, then you should enable SSL by setting email_ssl = true."
      required: true
      default: "smtp.mydomain.com"
      type: "string"

    - variable: "EMAIL_SERVER_PORT"
      label: "Wise2C Registry Email Server Port"
      description: ""
      required: true
      default: "25"
      type: "int"

    - variable: "EMAIL_USERNAME"
      label: "Wise2C Registry Email Username"
      description: ""
      required: true
      default: "sample_admin@mydomain.com"
      type: "string"

    - variable: "EMAIL_PASSWORD"
      label: "Wise2C Registry Email Password"
      description: ""
      required: true
      default: "abc"
      type: "password"

    - variable: "EMAIL_FROM"
      label: "Wise2C Registry Email From"
      description: ""
      required: true
      default: "admin <sample_admin@mydomain.com>"
      type: "string"

    - variable: "EMAIL_SSL"
      label: "Wise2C Registry Email SSL"
      description: ""
      required: true
      default: false
      type: "boolean"

    - variable: "HARBOR_ADMIN_PASSWORD"
      label: "Wise2C Registry Admin Password"
      description: "The adminstrator's password. Note that the default username/password are admin/Harbor12345 ."
      required: true
      default: "Harbor12345"
      type: "password"

    - variable: "AUTH_MODE"
      label: "Wise2C Registry Auth Mode"
      description: "The type of authentication that is used. By default it is db_auth, i.e. the credentials are stored in a database. For LDAP authentication, set this to ldap_auth."
      required: true
      type: "enum"
      options:
        - db_auth
        - ldap_auth

    - variable: "LDAP_URL"
      label: "Wise2C Registry LDAP URL"
      description: "The LDAP endpoint URL (e.g. ldaps://ldap.mydomain.com). Only used when auth_mode is set to ldap_auth ."
      default: "ldaps://ldap.mydomain.com"
      type: "string"

    - variable: "LDAP_BASEDN"
      label: "Wise2C Registry LDAP BaseDN"
      description: "The basedn template for verifying the user's credential against an LDAP (e.g. uid=%s,ou=people,dc=mydomain,dc=com ) or an AD (e.g. CN=%s,OU=Dept1,DC=mydomain,DC=com) server. Only used when auth_mode is set to ldap_auth."
      default: "uid=%s,ou=people,dc=mydomain,dc=com"
      type: "string"

    - variable: "DB_PASSWORD"
      label: "Wise2C Registry DB Password"
      description: "The root password for the mySQL database used for db_auth. Change this password for any production use!"
      required: true
      default: "root123"
      type: "password"

    - variable: "SELF_REGISTRATION"
      label: "Wise2C Registry Self Registration"
      description: "Enable / Disable the ability for a user to register themselves. When disabled, new users can only be created by the Admin user, only an admin user can create new users in Harbor. NOTE: When auth_mode is set to ldap_auth, self-registration feature is always disabled, and this flag is ignored."
      required: true
      default: on
      type: "enum"
      options:
        - on
        - off

    - variable: "CUSTOMIZE_CRT"
      label: "Wise2C Registry Custromize CRT"
      description: "When this attribute is on, the prepare script creates private key and root certificate for the generation/verification of the regitry's token. The following attributes:crt_country, crt_state, crt_location, crt_organization, crt_organizationalunit, crt_commonname, crt_email are used as parameters for generating the keys. Set this attribute to off when the key and root certificate are supplied by external sources."
      required: true
      default: on
      type: "enum"
      options:
        - on
        - off

    - variable: "OFFICIAL_CRT_DIR"
      label: "Wise2C Registry Official CRT Forlder"
      description: ""
      default: "/"
      type: "string"

    - variable: "CRT_COUNTRY"
      label: "Wise2C Registry CRT Country"
      description: ""
      default: "CN"
      type: "string"

    - variable: "CRT_STATE"
      label: "Wise2C Registry CRT State"
      description: ""
      default: "SC"
      type: "string"

    - variable: "CRT_LOCATION"
      label: "Wise2C Registry CRT Location"
      description: ""
      default: "CD"
      type: "string"

    - variable: "CRT_ORGANIZATION"
      label: "Wise2C Registry CRT Organization"
      description: ""
      default: "WISE2C"
      type: "string"

    - variable: "CRT_ORGANIZATIONALUNIT"
      label: "Wise2C Registry CRT Organization Unit"
      description: ""
      default: "DEVELOP"
      type: "string"

    - variable: "CRT_COMMONNAME"
      label: "Wise2C Registry CRT Common Name"
      description: ""
      default: "reg.wise2c.com"
      type: "string"

    - variable: "CRT_EMAIL"
      label: "Wise2C Registry CRT Email"
      description: ""
      default: ""
      type: "string"

    - variable: "MAX_JOB_WORKERS"
      label: "Wise2C Registry MAX Job Workers"
      description: "The maximum number of replication workers in job service. For each image replication job, a worker synchronizes all tags of a repository to the remote destination. Increasing this number allows more concurrent replication jobs in the system. However, since each worker consumes a certain amount of network/CPU/IO resources, please carefully pick the value of this attribute based on the hardware resource of the host."
      required: true
      default: 3
      type: "int"

    - variable: "VERIFY_REMOTE_CERT"
      label: "Wise2C Registry Verify Rmote CRT"
      description: "This flag determines whether or not to verify SSL/TLS certificate when Harbor communicates with a remote registry instance. Setting this attribute to off will bypass the SSL/TLS verification, which is often used when the remote instance has a self-signed or untrusted certificate."
      required: true
      default: on
      type: "enum"
      options:
        - on
        - off

prepare:
  scale: 1
log:
  scale: 1
registry:
  scale: 1
mysql:
  scale: 1
ui:
  scale: 1
jobservice:
  scale: 1
