.catalog:
  name: "Wise2C-Registry"
  version: "v0.1"
  description: "Wise2c Docker Registry"
  uuid: registry-1
  questions: 
    - variable: "DBPASSWD"
      label: "Wise2C Registry Mysql Password"
      description: "wise2c registry database password."
      required: true
      default: "root123"
      type: "string"
    - variable: "URL"
      label: "Wise2C Registry URL"
      description: "wise2c registry URL(don't include 'http:')."
      required: true
      default: "reg.wise2c.com"
      type: "string"
    - variable: "UIRADMINPWD"
      label: "Wise2C Registry Admin Password"
      description: "wise2c registry admin password."
      required: true
      default: Harbor,123
      type: "string"
    - variable: "STORAGEDIR"
      label: "Wise2C Registry Backend Storage Forlder"
      description: "wise2c registry backend storage DIR."
      required: true
      default: "/registry/data"
      type: "string"
    - variable: "LOGDIR"
      label: "Wise2C Registry Log Forlder"
      description: "Forlder on which to storage wise2c registry logs"
      required: true
      default: "/registry/log"
      type: "string"
    - variable: "CFGDIR"
      label: "Wise2C Registry Config Forlder"
      description: "Forlder on which to storage wise2c registry configurations"
      required: true
      default: "/registry/config"
      type: "string"
    - variable: "MYSQLDIR"
      label: "Wise2C Registry Mysql Forlder"
      description: "Forlder on which to storage mysql configurations"
      required: true
      default: "/registry/config"
      type: "string"
      
registry-data-volume:
  scale: 1